HTTP/2 200 
date: Thu, 08 Oct 2026 05:31:27 GMT
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
vary: Accept,Accept-Encoding, Accept, X-Requested-With
etag: W/"c00633e685a86a31eccacad8bccb7eec4988ac40b81bc88be4ccae4ba037bf4e"
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset, Warning
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
server: github.com
accept-ranges: bytes
x-ratelimit-limit: 60
x-ratelimit-remaining: 55
x-ratelimit-used: 5
x-ratelimit-resource: core
x-ratelimit-reset: 1791441079
content-length: 4455
x-github-request-id: C4D9:C7368:1D5FAB:60818F:6AC72AAE
x-github-edge-region: iad

[
  {
    "id": 45811662381,
    "node_id": "PSH_kwLOU_DKlM8AAAAKqpZ-LQ",
    "before": "f47dcc33768a07972df447f4b2e1743225a701e8",
    "after": "3f02cc9bfdaf67fb1886dcf5413bae71eef99f1b",
    "ref": "refs/heads/main",
    "timestamp": "2026-10-08T05:28:50Z",
    "activity_type": "push",
    "actor": {
      "login": "theruviparambil",
      "id": 139271432,
      "node_id": "U_kgDOCE0dCA",
      "avatar_url": "https://avatars.githubusercontent.com/u/139271432?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/theruviparambil",
      "html_url": "https://github.com/theruviparambil",
      "followers_url": "https://api.github.com/users/theruviparambil/followers",
      "following_url": "https://api.github.com/users/theruviparambil/following{/other_user}",
      "gists_url": "https://api.github.com/users/theruviparambil/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/theruviparambil/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/theruviparambil/subscriptions",
      "organizations_url": "https://api.github.com/users/theruviparambil/orgs",
      "repos_url": "https://api.github.com/users/theruviparambil/repos",
      "events_url": "https://api.github.com/users/theruviparambil/events{/privacy}",
      "received_events_url": "https://api.github.com/users/theruviparambil/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    }
  },
  {
    "id": 45696846823,
    "node_id": "PSH_kwLOU_DKlM8AAAAKo76L5w",
    "before": "f47dcc33768a07972df447f4b2e1743225a701e8",
    "after": "0000000000000000000000000000000000000000",
    "ref": "refs/tags/bypass-test/1",
    "timestamp": "2026-10-07T05:32:00Z",
    "activity_type": "branch_deletion",
    "actor": {
      "login": "theruviparambil",
      "id": 139271432,
      "node_id": "U_kgDOCE0dCA",
      "avatar_url": "https://avatars.githubusercontent.com/u/139271432?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/theruviparambil",
      "html_url": "https://github.com/theruviparambil",
      "followers_url": "https://api.github.com/users/theruviparambil/followers",
      "following_url": "https://api.github.com/users/theruviparambil/following{/other_user}",
      "gists_url": "https://api.github.com/users/theruviparambil/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/theruviparambil/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/theruviparambil/subscriptions",
      "organizations_url": "https://api.github.com/users/theruviparambil/orgs",
      "repos_url": "https://api.github.com/users/theruviparambil/repos",
      "events_url": "https://api.github.com/users/theruviparambil/events{/privacy}",
      "received_events_url": "https://api.github.com/users/theruviparambil/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    }
  },
  {
    "id": 45696251969,
    "node_id": "PSH_kwLOU_DKlM8AAAAKo7V4QQ",
    "before": "0000000000000000000000000000000000000000",
    "after": "f47dcc33768a07972df447f4b2e1743225a701e8",
    "ref": "refs/heads/main",
    "timestamp": "2026-10-07T05:22:50Z",
    "activity_type": "branch_creation",
    "actor": {
      "login": "theruviparambil",
      "id": 139271432,
      "node_id": "U_kgDOCE0dCA",
      "avatar_url": "https://avatars.githubusercontent.com/u/139271432?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/theruviparambil",
      "html_url": "https://github.com/theruviparambil",
      "followers_url": "https://api.github.com/users/theruviparambil/followers",
      "following_url": "https://api.github.com/users/theruviparambil/following{/other_user}",
      "gists_url": "https://api.github.com/users/theruviparambil/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/theruviparambil/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/theruviparambil/subscriptions",
      "organizations_url": "https://api.github.com/users/theruviparambil/orgs",
      "repos_url": "https://api.github.com/users/theruviparambil/repos",
      "events_url": "https://api.github.com/users/theruviparambil/events{/privacy}",
      "received_events_url": "https://api.github.com/users/theruviparambil/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    }
  }
]
